---
- name: ensure .ssh directory exists.
  file:
    dest: ~/.ssh
    mode: "0700"
    state: directory

- name: include bovbel ssh config
  blockinfile:
    marker: "# {mark} include bovbel ssh config"
    path: "~/.ssh/config"
    block: |
      Host *.bovbel.com
        ForwardAgent yes
        IdentityFile ~/.ssh/id_rsa
    state: present
    create: true

- name: install ssh key
  copy:
    src: vault/id_rsa
    dest: ~/.ssh/id_rsa
    mode: "0600"

- name: install ssh public key
  copy:
    src: id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    mode: "0600"

- name: Ensure .gnupg directory exists.
  file:
    dest: ~/.gnupg
    mode: "0700"
    state: directory

- name: Install gpg configs
  copy:
    src: "{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    mode: "0600"
  with_items:
    - gpg.conf
    - gpg-agent.conf

- name: Receive personal public key
  command: "/usr/bin/gpg --keyserver keyserver.ubuntu.com --recv {{ pgp_key_id }}"
