---
apt_remove:
  - packages: []

apt_install:
  - packages: []
    repo: "deb http://archive.canonical.com/ubuntu/ {{ ansible_distribution_release }} partner"
    filename: /etc/apt/sources.list

  - packages:
      # for dev
      - openssh-server
      - openssh-client
      - ubuntu-restricted-extras
      - va-driver-all
      - vainfo
      - libva2
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
      - swapspace
      - iperf
      - htop
      - ipython3
      - vlc
      - solaar-gnome3
      - net-tools
      - remmina
      - wireshark-qt
      - tcpdump
      - gnome-tweaks
      - flatpak

  - packages: ["kitty"]
    repo: "ppa:yurivkhan/kitty"
    filename: kitty

  - packages: ["code"]
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    keyurl: https://packages.microsoft.com/keys/microsoft.asc
    filename: code

flatpak_install:
  - com.slack.Slack
  - org.mozilla.firefox
  - org.freedesktop.Platform.ffmpeg-full/x86_64/21.08
  - org.gtk.Gtk3theme.Yaru-dark
  - com.spotify.Client
  - org.gimp.GIMP
  - org.inkscape.Inkscape
  - org.signal.Signal
  - us.zoom.Zoom

# vscode:
#   extensions:
#     - akamud.vscode-theme-onedark
