---
caddy_version: 2.9.1
caddy_plugins:
  - github.com/greenpau/caddy-security@v1.1.29
  - github.com/caddy-dns/route53@v1.5.1

docker_caddy:
  services:
    caddy:
      build:
        context: /etc/caddy/
      container_name: caddy
      networks:
        - apps
      ports:
        - 80:80
        - 443:443
      restart: "no"
      volumes:
        - /etc/caddy:/etc/caddy:ro
        - "{{ app_folder }}/caddy/data:/data"
        - "{{ app_folder }}/caddy/config:/config"
        - "{{ share_folder }}:/share:ro"
        - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      environment:
        TZ: America/Toronto
    filebrowser:
      image: filebrowser/filebrowser
      container_name: filebrowser
      networks:
        - apps
      volumes:
        - "{{ share_folder }}:/srv"
        - "{{ app_folder }}/filebrowser/filebrowser.db:/database.db"
      command: "-b /browser"

# Disable port forwards. HTTP(S) should work over tailscale.
upnp_forwards_caddy: {}
  # http: {from: 80, to: 80, proto: tcp}
  # https: {from: 443, to: 443, proto: tcp}

caddy: {}
caddy_defaults:
  users: []
  roles:
    - admin
    - share
  endpoints:
    share:
      type: share
      auth: oauth
      path: /share
      role: share
    browser:
      type: proxy
      auth: oauth
      path: /browser
      host: filebrowser
      port: 80
      role: admin
  token_secret: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') | to_uuid }}"
