---
- name: install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: enable and start fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started
  become: true

- name: configure fail2ban logging to journal
  lineinfile:
    dest: "/etc/fail2ban/fail2ban.conf"
    regexp: '^#?\s*logtarget.*'
    value: "logtarget = SYSOUT"
  become: true
  notify: restart fail2ban

- name: configure caddy fail2ban filter
  copy:
    dest: '/etc/fail2ban/filter.d/caddy-basic-auth.conf'
    content: |
      # fail2ban filter configuration for caddy basicauth
      [Definition]
      failregex = ^.*"remote_ip": "<HOST>".*"Authorization": \["REDACTED"\].*"status": 401.*$
      ignoreregex =
  become: true
  notify: restart fail2ban

- name: configure caddy fail2ban jail
  blockinfile:
    marker: "# {mark} include caddy fail2ban config"
    path: '/etc/fail2ban/jail.d/caddy-basic-auth.conf'
    block: |
      [caddy-basic-auth]
      enabled  = true
      chain    = DOCKER-USER
      port     = http,https
      backend  = systemd
      journalmatch = _SYSTEMD_UNIT=caddy.service
    state: present
    create: true
  become: true
  notify: restart fail2ban

- name: create caddy directory
  file:
    path: /etc/caddy/
    state: directory
  become: true

- name: create dockerfile
  template:
    src: Dockerfile.j2
    dest: /etc/caddy/Dockerfile
  become: true
  tags: docker

- name: configure caddy defaults
  set_fact:
    caddy: "{{ caddy | combine(caddy_defaults, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure caddy
  tags: caddy

- name: configure caddy docker
  set_fact:
    docker: "{{ docker | combine(docker_caddy, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure docker
  tags: docker

- name: configure caddy upnp
  set_fact:
    upnp_forwards: "{{ upnp_forwards | combine(upnp_forwards_caddy, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure upnp
  tags: upnp

- name: allow caddy access to tailscale agent
  lineinfile:
    dest: /etc/default/tailscaled
    regexp: '^TS_PERMIT_CERT_UID=.*$'
    line: 'TS_PERMIT_CERT_UID=caddy'
  become: true
  notify:
    - restart tailscale
