---
- name: add tailscale apt key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.gpg
    keyring: /etc/apt/trusted.gpg.d/tailscale.gpg
    state: present
  become: true

- name: add tailscale apt repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  become: true

- name: install tailscale agent
  apt:
    name:
      - jq
      - tailscale
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: start tailscale
  systemd:
    name: tailscaled
    state: started
    enabled: true
  become: true

- name: authorize tailscale
  when: tailscale is not defined or tailscale.BackendState != "Running" or tailscale.CurrentTailnet.Name != tailscale_tailnet

  block:
    - name: authorize machine
      shell: >
        "tailscale up --authkey '{{ tailscale_oauth_secret }}?ephemeral=false'
        --advertise-tags tag:{{ tailscale_tag }} {{ '--advertise-exit-node' if tailscale_exit_node }}"
      become: true

    - name: re-gather tailscale facts
      setup:
- name: configure tailscale upnp
  set_fact:
    upnp_forwards: "{{ upnp_forwards | combine(upnp_forwards_tailscale, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure upnp
  tags: upnp
