FROM caddy:{{ caddy_version }}-builder AS builder

RUN xcaddy build \
{% for plugin in caddy_plugins %}
    --with {{ plugin }}
{% endfor %}


FROM caddy:{{ caddy_version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

RUN apk add --no-cache tzdata
