---
- name: enable upnp update
  systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
    daemon_reload: true
    no_block: true
  become: true
  with_items:
    - upnp-update.timer
    - upnp-update.service

- name: configure upnp
  include_tasks: handlers/configure-upnp.yaml
