---
- name: restart netfilter-persistent
  service:
    name: netfilter-persistent
    state: restarted
  become: true

- name: restart sonarr
  service:
    name: sonarr
    state: restarted
  become: true

- name: restart radarr
  service:
    name: radarr
    state: restarted
  become: true

- name: restart jackett
  service:
    name: jackett
    state: restarted
  become: true

- name: restart deluge
  service:
    name: deluge
    state: restarted
  become: true

- name: restart tautulli
  service:
    name: tautulli
    state: restarted
  become: true

- name: enable cleanup-downloads
  systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
    daemon_reload: true
    no_block: true
  become: true
  with_items:
    - cleanup-downloads.timer
    - cleanup-downloads.service

- name: enable myanonamouse
  systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
    daemon_reload: true
  become: true
  with_items:
    - myanonamouse.timer
    - myanonamouse.service

- name: enable rip-to-audio
  systemd:
    name: "{{ item }}"
    enabled: true
    state: "started"
    daemon_reload: true
  become: true
  with_items:
    - rip-to-audio.timer
    - rip-to-audio.service
