---
- name: configure media server caddy
  set_fact:
    caddy: "{{ caddy | combine(caddy_media_server, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure caddy
  tags: caddy

- name: configure media server docker
  set_fact:
    docker: "{{ docker | combine(docker_media_server, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure docker
  tags: docker

- name: configure media server upnp
  set_fact:
    upnp_forwards: "{{ upnp_forwards | combine(upnp_forwards_media_server, recursive=True, list_merge='append') }}"
    cacheable: true
  changed_when: true
  notify: configure upnp
  tags: upnp

- name: setup cleanup downloads timer
  copy:
    content: |
      [Unit]
      Description=Cleanup old downloads from {{ downloads_folder }}

      [Timer]
      OnCalendar=04:30
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/cleanup-downloads.timer
  become: true
  notify: enable cleanup-downloads

- name: setup cleanup downloads service
  copy:
    content: |
      [Unit]
      Description=Cleanup old downloads from {{ downloads_folder }}

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/find {{ downloads_folder }} -maxdepth 1 -mtime +{{ cleanup_downloads_age }} -exec rm -rf {} \;
    dest: /etc/systemd/system/cleanup-downloads.service
  become: true
  notify: enable cleanup-downloads

# TODO(pbovbel) Update VPN IP with tracker.Ideally need a way to run this after container interface wg0 comes up,
# maybe extend the supervisord config in the container?
- name: create myanonamouse script
  template:
    src: mam-ip-update.j2
    dest: /usr/local/bin/mam-ip-update
    mode: "0777"
  become: true
  when: mam_id is defined
  notify: enable myanonamouse
  tags: mam_id

- name: setup myanonamouse service
  copy:
    content: |
      [Unit]
      Description=Update myanonamouse

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/mam-ip-update
      User={{ ansible_user }}
      Restart=no

    dest: /etc/systemd/system/myanonamouse.service
  become: true
  when: mam_id is defined
  notify: enable myanonamouse

- name: setup myanonamouse timer
  copy:
    content: |
      [Unit]
      Description=Update myanonamouse

      [Timer]
      OnCalendar=hourly
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/myanonamouse.timer
  become: true
  when: mam_id is defined
  notify: enable myanonamouse

- name: create rip-to-audio script
  copy:
    src: rip-to-audio
    dest: /usr/local/bin/rip-to-audio
    mode: "0777"
  become: true

- name: setup rip-to-audio service
  copy:
    content: |
      [Unit]
      Description=Rip audio

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/rip-to-audio '{{ tv_folder }}/Jeopardy!' '{{ audiobooks_folder }}/Jeopardy!' {{ plex_token }}
      User={{ ansible_user }}
      Restart=no

    dest: /etc/systemd/system/rip-to-audio.service
  become: true
  notify: enable rip-to-audio

- name: setup rip-to-audio timer
  copy:
    content: |
      [Unit]
      Description=Rip audio

      [Timer]
      OnCalendar=daily
      Persistent=true

      [Install]
      WantedBy=timers.target
    dest: /etc/systemd/system/rip-to-audio.timer
  become: true
  notify: enable rip-to-audio

# - name: configure jackett basepath
#   replace:
#     path: "{{ app_folder }}/jackett/Jackett/ServerConfig.json"
#     regexp: '"BasePathOverride": ".*",'
#     replace: '"BasePathOverride": "/jackett",'
#   notify: restart jackett

# - name: configure radarr basepath
#   replace:
#     path: "{{ app_folder }}/radarr/config.xml"
#     regexp: '<UrlBase>.*</UrlBase>'
#     replace: '<UrlBase>radarr</UrlBase>'
#   notify: restart radarr

# - name: configure readarr basepath
#   replace:
#     path: "{{ app_folder }}/readarr/config.xml"
#     regexp: '<UrlBase>.*</UrlBase>'
#     replace: '<UrlBase>readarr</UrlBase>'
#   notify: restart readarr

# - name: configure sonarr basepath
#   replace:
#     path: "{{ app_folder }}/sonarr/config.xml"
#     regexp: '<UrlBase>.*</UrlBase>'
#     replace: '<UrlBase>sonarr</UrlBase>'
#   notify: restart sonarr

# - name: configure tautulli basepath
#   replace:
#     path: "{{ app_folder }}/tautulli/config.ini"
#     regexp: 'http_root = ".*"'
#     replace: 'http_root = tautulli'
#   notify: restart tautulli

# - name: configure tautulli proxy
#   replace:
#     path: "{{ app_folder }}/tautulli/config.ini"
#     regexp: 'http_proxy = .*'
#     replace: 'http_proxy = 1'
#   notify: restart tautulli

# - name: configure bazarr proxy
#   replace:
#     path: "{{ app_folder }}/bazarr/config/config.ini"
#     regexp: 'base_url = .*'
#     replace: 'base_url = /bazarr'
#   notify: restart bazarr

# - name: configure mylar3 proxy
#   replace:
#     path: "{{ app_folder }}/mylar3/mylar/config.ini"
#     regexp: 'http_root = .*'
#     replace: 'http_root = /mylar'
#   notify: restart bazarr

# - name: configure deluge thin client auth
#   lineinfile:
#     dest: "{{ app_folder }}/deluge/auth"
#     line: "{{ web_user }}:{{ web_password }}:10"
#   notify: restart deluge
