---
name: ansible lint

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Cache ansible
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: ${{ hashFiles('requirements.yaml') }}

      - name: write vault_pass to file
        run: echo $VAULT_PASS >> vault_pass.txt
        shell: bash
        env:
          VAULT_PASS : ${{ secrets.VAULT_PASS }}

      - name: Run ansible-lint
        shell: bash
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          ansible-lint
